services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    
    volumes:
      - ./api:/app
      - ./data:/app/data
  # ollama: 
  #   build:
  #     context: ollama
  #   volumes: 
  #     - ./data/ollama:/root/.ollama
  #   ports:
  #     - 11434:11434 
 