[project]
name = "project-zeno"
version = "0.1.0"
description = "Language Interface for Maps & WRI/LCL data APIs."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.7",
    "langchain-anthropic>=0.2.4",
    "langchain-community>=0.3.5",
    "langchain-ollama>=0.2.0",
    "langchain-openai>=0.2.6",
    "streamlit>=1.40.0",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.3.0",
]
